name: MCPEToDiscord
authors: 
  - JaxkDev
  - GamerMJay
version: 2.3.1
api: 5.0.0
main: Jack\MCPEToDiscord\Main

commands:
  mcpe:
    description: Discord commands use /mcpe help for all cmds
    permission: mcpetodiscord.use
    aliases: ["mcpetodiscord"]

permissions: 
  mcpetodiscord.use:
    default: op
