name: MCPEToDiscord
author: JaxkDev
version: 2.2.2-Beta
api: 4.0.0
main: Jack\MCPEToDiscord\Main

commands:
  mcpe:
    description: Discord commands use /mcpe help for all cmds
    permission: mcpetodiscord.use
    usage: /mcpe help
    aliases: ["mcpetodiscord"]

permissions: 
  mcpetodiscord.use:
    default: op
